input.onPinPressed(TouchPin.P0, function () {
    radio.sendNumber(0)
    music.playTone(262, music.beat(BeatFraction.Whole))
    music.playTone(294, music.beat(BeatFraction.Whole))
    music.playTone(330, music.beat(BeatFraction.Whole))
})
input.onButtonPressed(Button.A, function () {
    basic.showString("BT-F")
    basic.pause(100)
    basic.clearScreen()
})
input.onButtonPressed(Button.B, function () {
    basic.showString("v1.1")
    basic.pause(100)
    basic.clearScreen()
})
radio.setGroup(33)
radio.setTransmitPower(7)
music.setBuiltInSpeakerEnabled(true)
music.setVolume(255)
basic.showIcon(IconNames.StickFigure)
basic.pause(100)
basic.clearScreen()
